### ISSUE TITLE
[2.1.0] target contains mixed language source files; feature not supported

### ISSUE THREAD

**Issue by Dean151** [calimarkus/JDStatusBarNotification#133] opened 2023-11-02 13:00 UTC
Xcode 15.0.1 doesn't want to build latest version 2.1.0 of the library, with the following error:
```
 Showing All Messages target at '/Users/<redacted>/Library/Developer/Xcode/DerivedData/<redacted>/SourcePackages/checkouts/JDStatusBarNotification' contains mixed language source files; feature not supported
```

**Comment by calimarkus** [comment] 2023-11-02 20:09
Thanks for the report. I don't see a problem locally with `Xcode Version 15.0.1 (15A507)` on a `iOS 17.0.1` Simulator.

- Which target did you try to build?
- On device or simulator?
- Which iOS version?
- Did you also try using it in a project? E.g. through SPM or cocoapods?

**Comment by Dean151** [comment] 2023-11-02 20:50
Hi!

The error is not occurring while building, but while SPM is resolving the dependencies.
So I'm using SPM, on an app targeting iOS 16+, watchOS 9+

Seems related to this: https://stackoverflow.com/questions/51540665/swift-package-manager-mixed-language-source-files
Different languages should be moved in different targets

**Comment by calimarkus** [comment] 2023-11-02 22:11
Thank you! I have a working version in this branch, if that helps you in any way: https://github.com/calimarkus/JDStatusBarNotification/commits/fix_spm_mixed_language

But I still need test/fix a few things before I'll publish a new version.

This article was super helpful:
https://joesusnick.medium.com/swift-package-manager-with-a-mixed-swift-and-objective-c-project-part-2-2-e71dad234e6

**Comment by haarj** [comment] 2023-11-03 15:32
`fix_spm_mixed_language` works in building but it doesn't break some objc code that I have

**Comment by calimarkus** [comment] 2023-11-03 15:33
How so? Could you share some more details?

**Comment by haarj** [comment] 2023-11-03 15:36
Also this break where "dismissAfterDelay" isn't available anymore. 

 `NotificationPresenter.shared().present(text: NSLocalizedString("EVENT_ADDED", comment: ""),
                                                       dismissAfterDelay: 2,
                                                       includedStyle: .defaultStyle)`

I get an undeclared error where Xcode doesn't recognize this anymore.
`[[JDStatusBarNotificationPresenter sharedPresenter]`

**Comment by calimarkus** [comment] 2023-11-04 14:28
@haarj 

1)
`NotificationPresenter.shared().present(text:dismissAfterDelay:includedStyle:)` is now:
`NotificationPresenter.shared().present(_:includedStyle:duration:)`

2)
`[JDStatusBarNotificationPresenter sharedPresenter]` works for me. Could you describe your setup / how you integrated the library? Through SPM? Cocoapods? Manual?

**Comment by haarj** [comment] 2023-11-05 12:01
Nevermind. I had to import `JDStatusBarNotificationObjC` instead of `JDStatusBarNotification` now and it worked.

**Comment by calimarkus** [comment] 2023-11-05 15:51
@haarj glad to hear that, but that shouldn't be needed. You're using spm and you're importing in an obj file, correct? I'd like to reproduce that.

**Comment by haarj** [comment] 2023-11-05 15:53
Yes I am using SPM and was importing the original and using objc code before the update.Sent from my iPhoneOn Nov 5, 2023, at 10:51 AM, M Emrich ***@***.***> wrote:﻿
@haarj glad to hear that, but that shouldn't be needed. You're using spm and you're importing in an obj file, correct? I'd like to reproduce that.

**Comment by calimarkus** [comment] 2023-11-05 20:58
Ah I see. If I use a module import (`@import JDStatusBarNotification`) I can see the same issue.
If I use `#import "JDStatusBarNotification.h"` I don't see the issue - as the module is automatically resolved.

I'm checking if I can resolve this.

**Comment by calimarkus** [comment] 2023-11-05 22:11
This is now resolved and merged to `main`. I also tagged a new version as `2.1.1`.

**Closed by calimarkus** 2023-11-05 22:11 UTC

**Comment by calimarkus** [comment] 2023-12-10 19:27
FYI @haarj the latest 2.2.0 version will require the regular module import again in ObjC:
- `@import JDStatusBarNotification;` - just as before.

The `JDStatusBarNotificationObjC` module no longer exists.

For Swift nothing changes.

**Comment by haarj** [comment] 2023-12-11 14:45
ok great! Thanks for letting me know!
